---
apiVersion: v1
kind: Pod
metadata:
  name: postgress
  labels:
    type: clusterip
spec:
  containers:
    - name: postgress
      image: postgress
      env:
        - name: POSTGRESS_PASSWORD
          value: mohan 
        - name: POSTGRESS_USER
          value: mohan
        - name: POSTGRESS_DB  
          value: mydb
---
apiVersion: v1
kind: Service
metadata:
  name: service-clusterip
  labels:
    type: clusterip
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    type: clusterip
...      
