---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels: 
    type: ci-cd
spec:
  containers:
    - name: jenkins-pod
      image: jenkins/jenkins
---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    type: ci-cd
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30002
...        
