---
apiVersion: v1
kind: Namespace
metadata:
  name: space

---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels: 
    type: namespace
  namespace: space
spec:
  containers:
    - name: wordpress-pod
      image: wordpress
      ports:
        - containerPort: 80
          hostPort: 8080
...
