---
apiVersion: v1
kind: Pod
metadata: 
  name: nodeaffinity
  labels:
    type: affinity
spec:
  containers:
    - name: nginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave1
                operator: In
                values:
                  - slave2
...
