---
apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    type: nodeport
spec:
  containers:
    - name: nginx
      image: nginx
---

apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    type: nodeport
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30001
  selector:
    type: nodeport    
...
