---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate
  labels:
    type: recreate
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      type: recreate
  template:      
    metadata:
      name: recreate
      labels:
        type: recreate  
    spec:    
      containers:
        - name: nginx
          image: nginx:1.24
          ports: 
            - containerPort: 8080
              hostPort: 8080         

...
