---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    type: proxy
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-rc
      labels:
        type: proxy
    spec:  
      containers:
        - name: nginx-pod
          image: nginx
          ports:
            - containerPort: 8080
              hostPort: 80  
...                  
