---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rc
  labels:
    type: none
spec:
  replicas: 2
  selector: 
    matchLabels: 
      type: none
  template:
    metadata:
      name: httpd
      labels:
        type: none
    spec:    
      containers:
        - name: httpd-pod
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 80

...
