---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling
  labels:
    type: updates
spec:
  replicas: 2
  selector: 
    matchLabels:
      type: updates
  template:
    metadata:
      name: update-pod
      labels:  
        type: updates
    spec:    
      containers:
        - name: nginx
          image: nginx:1.24
          ports:
            - containerPort: 80
              hostPort: 80   
                
...
