---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  labels:
    type: mydb
type: Opaque
stringData:
  password: mypasswd  

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    type: db
spec:
  containers:
    - name: mysql
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: password
           
...                    
