---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  labels:
    type: privacy
type: Opaque
stringData:
  passwd: opaque
  user: mohan
  db: mydb
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress
  labels:
    type: privacy
spec:
  replicas: 2
  selector:
    matchLabels:
      type: privacy
  template:
    metadata:
      name: postgress
      labels:
        type: privacy  
    spec:    
      containers:
        - name: postgress-pod
          image: postgress
          env:
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: passwd
            - name: POSTGRESS_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: user
            - name: POSTGRESS_DB
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db   
...                    
