---
apiVersion: v1
kind: Pod
metadata:
  name: volumes
  labels:
    type: volume
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: myvolume
          mountPath: /data/redis
  volumes:
    - name: myvolume
      emptyDir: {}    
...
